apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: statusquarkusio-605v
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-zaer-tenant/status-quarkus-io/statusquarkusio-605v@sha256:bcb351c1159cd6fc11b06ef5f1851c8e58f1ce56f4e7d2c2b277baff38aa5152
        name: my-java-quarkus
        resources: {}
status: {}
